---
title: "1349 daily"
author: "Junsong Tang"
date: '2022-07-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tseries)
library(xts)
library(zoo)
library(tidyverse)
library(forecast)
library(stlplus)
library(seasonal)
library(L1pack)


```


# watershed 1349 has snow fraction 2%

```{r, echo=TRUE}
data1349 = DATA[[1349]]
daily1349 = as.daily(data1349)
# identifying the range of NA
daily1349[is.na(daily1349$resp),]

ts1349 = ts(log(daily1349$resp), start=c(1980,1), frequency = 365)
plot(ts1349, ylim=c(-6,6))
acf(ts1349, lag.max = 365*5, main = "acf of daily response", na.action = na.pass)
pacf(ts1349, lag.max = 365*5, main = "pacf of daily respoonse", na.action = na.pass)
```


```{r, echo=TRUE}
spec1349 = spectrum(ts1349, na.action=na.exclude, xlim = c(0,0.02), ylim=c(10, 10000), type = "h")
spec_chart1349 = data.frame(period=1/spec1349$freq, frequency=spec1349$freq, spectrum=spec1349$spec)
head(spec_chart1349[order(spec_chart1349$spectrum, decreasing=TRUE),], 10)

```


#stl plus
```{r, echo=TRUE}
stlp1349 = stlplus(ts1349, n.p=365, s.window="periodic", inner=2, outer=10)
# my_s = seasonal.loess(ts1409, deg=1, span=0.1273659)
# my_t = trend.loess(ts1409-my_s, deg=1, span=0.0008491057)
plot(stlp1349)

```



# seasonality
```{r, echo=TRUE}
decomp1349 = decompose.loess(ts1349)
```



```{r, echo=TRUE}
# trend compare
plot(ts1349, type="l", col="green", ylim=c(-6,6), main="1349 trend compare")
lines(decomp1349$trend, col="red")
lines(ts(stlp1349$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))


# seasonal compare
plot(ts1349, type="l", col="green", xlim=c(1980,1982), ylim=c(-6,6), main="1349 seasonal compare")
lines(decomp1349$seasonal, col="red")
lines(ts(stlp1349$data[,"seasonal"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))


# remainder compare
plot(ts1349, type="l", col="green", ylim=c(-6,6), main="1349 remainder compare")
lines(decomp1349$remainder, col="red")
lines(ts(stlp1349$data[,"remainder"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))

```



```{r, echo=TRUE}
mean((ts1349 - decomp1349$trend)^2, na.rm=TRUE)
mean((ts1349 - ts(stlp1349$data[,"trend"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)

mean((ts1349 - decomp1349$seasonal)^2, na.rm=TRUE)
mean((ts1349 - ts(stlp1349$data[,"seasonal"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)


mean((decomp1349$remainder)^2, na.rm = TRUE)
mean((ts(stlp1349$data[,"remainder"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)

```








# model
```{r, echo=TRUE}
model = arima(error, order = c(3,0,0), include.mean = TRUE)
acf(model$residuals)
pacf(model$residuals, lag.max = 365)
tsdiag(model)
qqnorm(model$residuals)
qqline(model$residuals)
hist(model$residuals)

```



