---
title: '1458'
author: "Junsong Tang"
date: '2022-07-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tseries)
library(xts)
library(zoo)
library(tidyverse)
library(forecast)
library(stlplus)
library(seasonal)
library(L1pack)
```



# watershed 1458 has the largest snow fraction of all, which is 66%

```{r, echo=TRUE}
data1458 = DATA[[1458]]
daily1458 = as.daily(data1458)
# identifying the range of NA
daily1458[is.na(daily1458$resp),]

ts1458 = ts(log(daily1458$resp), start=c(1980,1), frequency = 365)
plot(ts1458, ylim=c(-5,5))
acf(ts1458, lag.max = 365*5, main = "acf of daily response", na.action = na.pass)
pacf(ts1458, lag.max = 365*5, main = "pacf of daily respoonse", na.action = na.pass)
```

```{r, echo=TRUE}
spec1458 = spectrum(ts1458, na.action=na.exclude, xlim = c(0,0.02), ylim=c(10, 10000), type = "h")
spec_chart1458 = data.frame(period=1/spec1458$freq, frequency=spec1458$freq, spectrum=spec1458$spec)
head(spec_chart1458[order(spec_chart1458$spectrum, decreasing=TRUE),], 10)

```



#stl plus
```{r, echo=TRUE}
stlp1458 = stlplus(ts1458, n.p=365, s.window="periodic", inner=2, outer=10)
# my_s = seasonal.loess(ts1409, deg=1, span=0.1273659)
# my_t = trend.loess(ts1409-my_s, deg=1, span=0.0008491057)
plot(stlp1458)

```



# seasonality
```{r, echo=TRUE}
decomp1458 = decompose.loess.plus(ts1458)
```



```{r, echo=TRUE}
# trend compare
plot(ts1458, type="l", col="green", ylim=c(-5,5), main="1458 trend compare")
lines(decomp1458$component$trend, col="red")
lines(ts(stlp1458$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))


# seasonal compare
plot(ts1458, type="l", col="green", xlim=c(1980,1982), ylim=c(-5,5), main="1458 seasonal compare")
lines(decomp1458$component$seasonal, col="red")
lines(ts(stlp1458$data[,"seasonal"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))


# remainder compare
plot(ts1458, type="l", col="green", ylim=c(-5,5), main="1458 remainder compare")
lines(decomp1458$component$remainder, col="red")
lines(ts(stlp1458$data[,"remainder"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1, col=c("green","red", "blue"))

```




```{r, echo=TRUE}
# mean((ts1458 - decomp1458$component$trend)^2, na.rm=TRUE)
# mean((ts1458 - ts(stlp1458$data[,"trend"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)
# 
# mean((ts1458 - decomp1458$component$seasonal)^2, na.rm=TRUE)
# mean((ts1458 - ts(stlp1458$data[,"seasonal"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)


mean((decomp1458$component$remainder)^2, na.rm = TRUE)
mean((ts(stlp1458$data[,"remainder"], start =c(1980,1), frequency = 365))^2, na.rm=TRUE)

```


#=========================================================================================Model


```{r, echo=TRUE}
# check if the remainder has any seasonal leftover
plot(ts1458, type="l", col="green", ylim=c(-5,5))
lines(seasonal.loess(decomp1458$component$remainder, deg=1, window=decomp1458$seasonal.window), col="red")

acf(decomp1458$component$remainder, lag.max = 50, main = "acf of daily response", na.action = na.pass)
pacf(decomp1458$component$remainder, lag.max = 50, main = "pacf of daily respoonse", na.action = na.pass)

acf(ts(stlp1458$data[,"remainder"], start =c(1980,1), frequency = 365), lag.max = 365,  na.action = na.pass)
pacf(ts(stlp1458$data[,"remainder"], start =c(1980,1), frequency = 365), lag.max = 50,  na.action = na.pass)

```




# model fitting
```{r, echo=TRUE}
model = arima(decomp1458$component$remainder, order = c(2,0,3), include.mean = TRUE)
acf(model$residuals, na.action = na.pass)
pacf(model$residuals, lag.max = 365, na.action = na.pass)
tsdiag(model)
qqnorm(model$residuals)
qqline(model$residuals)
hist(model$residuals)

```



