---
title: "watershed results"
author: "Junsong Tang"
date: '2022'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(tseries)
```




# 1409
```{r, echo=TRUE, warning=FALSE}
spans = seq(from=0.01, to=0.1, by=0.01)
vars = lapply(spans, FUN=function(x) {variation(ts1409, x)})
sv = sapply(vars, FUN=function(x){x$sv})
tv = sapply(vars, FUN=function(x){x$tv})
rv = sapply(vars, FUN=function(x){x$rv})
# s_spans = sapply(vars, FUN=function(x){x$s.span})

```

```{r, echo=TRUE}
plot(x = spans, y = sv, type = "b", ylim = c(0, 1), main = "variance", col = "green")
lines(x = spans, y = tv, type = "b", col = "blue")
lines(x = spans, y = rv, type = "b", col = "red")
legend("topright",legend=c("seasonal","trend", "remainder"), lty=1,
       col=c("green","blue", "red"))

```



```{r, echo=TRUE}
# t1 = trend(ts1409, window = 0.07*length(ts1409))
# s1 = seasonal(ts1409 - t1, deg = 2, window = 57*38)
# r1 = ts1409 - t1 - s1
# plot(ts1409, type = "l", col="green", ylim=c(-5,5), main="span = 0.07")
# lines(t1, col = "blue")
# lines(s1, col = "red")
start_time = Sys.time()
d1409 = decompose(ts1409, iter=3)
end_time = Sys.time()
end_time - start_time

```

```{r, echo=TRUE}
plot(ts1409, type="l", col="green", ylim=c(-5,5), main="1409 trend compare")
lines(d1409$component$trend + d1409$component$seasonal, col="blue")
# lines(ts(stlp1409$data[,"trend"], start =c(1980,1), frequency = 365) , col="red")
# lines(d$component$trend, col="blue")
# lines(d$component$seasonal, col="purple")
# lines(ts(stlp1409$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
# legend("topright",legend=c("ts","loess trend", "loess seasonal", "stl_plus trend"), lty=1,
#        col=c("green","red", "purple", "blue"))






# seasonal compare
plot(ts1409, type="b", col="green", xlim=c(1989,1990), main="1409 seasonal compare")
lines(d1409$component$seasonal+ d1409$component$trend, col="red")
lines(ts(stlp1409$data[,"seasonal"]+stlp1409$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1,
       col=c("green","red", "blue"))

```






# 1349
```{r, echo=TRUE}
# t1 = trend(ts1409, window = 0.07*length(ts1409))
# s1 = seasonal(ts1409 - t1, deg = 2, window = 57*38)
# r1 = ts1409 - t1 - s1
# plot(ts1409, type = "l", col="green", ylim=c(-5,5), main="span = 0.07")
# lines(t1, col = "blue")
# lines(s1, col = "red")
start_time = Sys.time()
d1349= decompose(ts1349, iter=3)
end_time = Sys.time()
end_time - start_time

```


```{r, echo=TRUE}
plot(ts1349, type="l", col="green", ylim=c(-5,5), main="1349")
lines(d1349$component$trend + d1349$component$seasonal, col="red")
# # lines(ts(stlp1409$data[,"trend"], start =c(1980,1), frequency = 365) , col="red")
# lines(d1349$component$trend, col="red")
# lines(d$component$seasonal, col="purple")
# lines(ts(stlp1349$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
# legend("topright",legend=c("ts","loess trend", "loess seasonal", "stl_plus trend"), lty=1,
#        col=c("green","red", "purple", "blue"))






# seasonal compare
plot(ts1349, type="b", col="green", xlim=c(2000,2005), main="1349 s+t")
lines(d1349$component$seasonal+ d1349$component$trend, col="red")
lines(ts(stlp1349$data[,"seasonal"]+stlp1349$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1,
       col=c("green","red", "blue"))

```


```{r, echo=TRUE, warning=FALSE}
spans = seq(from=0.01, to=0.1, by=0.01)
vars = lapply(spans, FUN=function(x) {variation(ts1349, x)})
sv = sapply(vars, FUN=function(x){x$sv})
tv = sapply(vars, FUN=function(x){x$tv})
rv = sapply(vars, FUN=function(x){x$rv})
# s_spans = sapply(vars, FUN=function(x){x$s.span})

```

```{r, echo=TRUE}
plot(x = spans, y = sv, type = "b", ylim = c(0, 2), main = "variation", col = "green")
lines(x = spans, y = tv, type = "b", col = "blue")
lines(x = spans, y = rv, type = "b", col = "red")
legend("topright",legend=c("seasonal","trend", "remainder"), lty=1,
       col=c("green","blue", "red"))

```





# 1369
```{r, echo=TRUE}
# t1 = trend(ts1409, window = 0.07*length(ts1409))
# s1 = seasonal(ts1409 - t1, deg = 2, window = 57*38)
# r1 = ts1409 - t1 - s1
# plot(ts1409, type = "l", col="green", ylim=c(-5,5), main="span = 0.07")
# lines(t1, col = "blue")
# lines(s1, col = "red")
start_time = Sys.time()
d1369= decompose(ts1369, iter=3)
end_time = Sys.time()
end_time - start_time

```


```{r, echo=TRUE}
plot(ts1369, type="l", col="green", ylim=c(-5,5), main="1369")
# lines(d1369$component$trend + d1369$component$seasonal, col="blue")
# lines(ts(stlp1409$data[,"trend"], start =c(1980,1), frequency = 365) , col="red")
lines(d1369$component$trend, col="red")
# lines(d$component$seasonal, col="purple")
lines(ts(stlp1369$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
# legend("topright",legend=c("ts","loess trend", "loess seasonal", "stl_plus trend"), lty=1,
#        col=c("green","red", "purple", "blue"))






# seasonal compare
plot(ts1369, type="b", col="green", xlim=c(1980,1983), main="1349 s+t")
lines(d1369$component$seasonal+ d1369$component$trend, col="red")
lines(ts(stlp1369$data[,"seasonal"]+stlp1369$data[,"trend"], start =c(1980,1), frequency = 365), col="blue")
legend("topright",legend=c("ts","loess", "stl_plus"), lty=1,
       col=c("green","red", "blue"))

```


```{r, echo=TRUE, warning=FALSE}
spans = seq(from=0.01, to=0.1, by=0.01)
vars = lapply(spans, FUN=function(x) {variation(ts1369, x)})
sv = sapply(vars, FUN=function(x){x$sv})
tv = sapply(vars, FUN=function(x){x$tv})
rv = sapply(vars, FUN=function(x){x$rv})
# s_spans = sapply(vars, FUN=function(x){x$s.span})

```

```{r, echo=TRUE}
plot(x = spans, y = sv, type = "b", ylim = c(0, 2), main = "variation", col = "green")
lines(x = spans, y = tv, type = "b", col = "blue")
lines(x = spans, y = rv, type = "b", col = "red")
legend("topright",legend=c("seasonal","trend", "remainder"), lty=1,
       col=c("green","blue", "red"))

```