---
title: "watershed uts utility"
author: "Junsong Tang"
date: '2022-07-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(tseries)
```




#=========================================================================================
# Format the time series
```{r, echo=TRUE}
# month-format
month.unify = function() {
  month = NULL
  for (m in (1:12)) {
    if ((m <= 7 && m %% 2 == 1) || (m >= 8 && m %% 2 == 0)) {
      month = c(month, rep(m, 31))
    } else if (m == 2) {
      month = c(month, rep(m, 28))
    } else {
      month = c(month, rep(m, 30))
    }
  }
  return (month)
}


# day-format
day.unify = function() {
  day = NULL
  for (m in (1:12)) {
    if ((m <= 7 && m %% 2 == 1) || (m >= 8 && m %% 2 == 0)) {
      day = c(day, seq(from = 1, to = 31, by = 1))
    } else if (m == 2) {
      day = c(day, seq(from = 1,to = 28,by = 1))
    } else {
      day = c(day, seq(from = 1,to = 30,by = 1))
    }
  }
  return (day)
}

```


# Daily structure
```{r, echo=TRUE}
# given a Rdata file, return a complete data frame(with covariates & response)
as.daily = function(data, impute=FALSE) {
  #start year
  start = data$yrs[1]
  # number of years
  n = length(data[[1]][, 1])
  
  # format unit month & days in calender
  month = month.unify()
  day = day.unify()
  # repeat unit format for n years
  months = rep(month, n)
  days = rep(day, n)
  # format years from 1980 to 
  years = rep(start:(start+n-1), each=365)
  
  frame = data.frame(years, months, days)
  
  # refined version
  for (k in (1:(length(data)-1))) {
    values = as.vector(t(data[[k]]))
    
    # # N/A & imputation if applicable
    # if (impute) {
    #   na_indices = which(is.na(values))
    #   # imputation method
    #   values[na_indices] = values[na_indices - 365]
    # }
    
    # some data file do not have covariate/resp lists of same length:
    # i.e. length(snow)=length(rain) != length(resp)
    if (dim(frame)[1] == length(values)) {
      frame = cbind(frame, values)
      names(frame)[k+3] = substr(names(data)[k], start=1, stop=4)
    }
    # # else, we could pad the shorter vector: length(values) = dim(frame)[1]
    # else {
    #   length(values) = dim(frame)[1]
    #   frame = cbind(frame, values)
    #   names(frame)[k+3] = names(data)[k]
    # }
  }
  
  # N/A & imputation if applicable
  if (impute) {
    l = dim(frame)[1]
    w = dim(frame)[2]
    for (i in (1:l)) {
      for (j in (4:w)) {
        if (is.na(frame[[j]][i])) {
          frame[[j]][i] = frame[[j]][i-365]
        }
      }
    }
  }
  
  
  
  # # original version
  # for (k in (1:(length(Rdata)-1))) {
  #   # data one of matrices in Rdata(cube) file
  #   mtx = Rdata[[k]]
  #   values = NULL
  #   for (i in (1:n)) {
  #     for (j in (1:length(mtx[1,]))) {
  #       values = c(values, mtx[i,j])
  #       
  #       #N/A & imputation if applicable
  #       if (impute) {
  #         ind = (i-1)*365 + j
  #         if (is.na(values[ind])) {
  #           values[ind] = values[ind-365]
  #         }
  #       }
  #       
  #     }
  #   }
  #   
  #   if (dim(frame)[1] == length(values)) {
  #     frame = cbind(frame, values)
  #     names(frame)[k+3] = names(Rdata)[k]
  #   }
  #   # else, we could pad the shorter vector: length(values) = dim(frame)[1]
  #   # frame = cbind(frame, values)
  #   # names(frame)[k+3] = names(Rdata)[k]
  # }
  return (frame)
}

```


# Monthly structure(smooth)
```{r, echo=TRUE}
as.monthly = function(data) {
  
  daily = as.daily(data, impute = FALSE)
  # start year
  start = daily$years[1]
  k = dim(daily)[2]-3 # total number of category(i.e. snow, rain, temp...)
  
  monthly = data.frame()
  
  year = NULL
  month = NULL
  
  m = 1 # month cursors
  sum = rep(0, k) # sum accumulator(row vector!)
  
  count = 0 # days accumulator
  ycount = 0 #  years accumulator
  for (i in (1:length(daily$months))) {
    # get all current values of snow, rain, temp, resp in vector
    curr = NULL
    for (j in (1:k)) {
      curr = c(curr, daily[[3+j]][i])
      # curr = c(curr, daily[i,(3+j)])
    }
    # curr = daily[i,][-(1:3)]: # this method is very slow!
    
    # sum: row vector
    # curr: row vector
    # avg: row vector
    # monthly: data frame/matrix
    
    # with the same month && not at December 31st
    if (m == daily$months[i] && i < length(daily$months)) {
      sum = sum + curr
      count = count + 1
    } # with the same month && at December 31st
    else if (m == daily$months[i] && i == length(daily$months)) {
      sum = sum + curr
      count = count + 1
      avg = sum / count
      monthly = rbind(monthly, avg)
      month = c(month, m)
      year = c(year, start+ycount)
    } # at the point of month change(1st day of next month)
    else {
      avg = sum / count
      monthly = rbind(monthly, avg)
      month = c(month, m)
      year = c(year, start+ycount)
      if (m == 12) {
        ycount = ycount + 1
      }
      m = daily$months[i]
      sum = curr
      count = 1
    }
  }
  # note k+3 = dim(daily)[2]
  names(monthly) = names(daily[4:(k+3)])
  return (data.frame(year, month, monthly))
}

```



```{r, echo=TRUE}
# window: fixed time window average of raw ts, i.e. weekly ts, 20 day avg ts
as.avg = function(data, window) {
  mts = mts(data)
  start_year = as.integer(tsp(mts[[1]])[1])
  freq = as.integer(tsp(mts[[1]])[3])
  n = length(mts[[1]])
  k = ceiling(n / window)
  
  df = data.frame()
  for (i in (1:length(mts))) {
    avg = NULL
    ts = mts[[i]]
    for (i in (0:(k-1))) {
      avg = c(avg, mean(ts[(i*window+1) : min(n,(i+1)*window)], na.rm=TRUE))
    }
    ts = ts(avg, start = c(start_year,1), frequency= freq / window)
    if (dim(df)[1] == 0) {
      df = data.frame(ts)
    } # if current ts has same length as previous ones
    else if (dim(df)[1] == length(ts)) {
      df = cbind(df, ts)
    } # if current ts differs in length from previous ones, then trim(longer)/pad(shorter)
    else {
      length(ts) = dim(df)[1]
      df = cbind(df, ts)
    }
    
  }
  names(df) = names(mts)
  
  return (df)
  
}


```






```{r, echo=TRUE}
# as.gasp.data = function(data, window) {
#   avg_mts = as.avg(data, window)
#   # number of years
#   k = length(data$yrs)
#   new_freq = as.integer(tsp(avg_mts$resp)[3])
#   index = seq(from=1, to=length(avg_mts$resp), by=1)
#   season = rep(c(1:new_freq), times = k)
#   year = rep(data$yrs, each=new_freq)
# 
#   df = data.frame(avg_mts, index, season, year)
#   return (df)
# }

# as.gasp.data = function(data, window) {
#   avg_mts = as.avg(data, window)
#   # number of years
#   k = length(data$yrs)
#   n = length(avg_mts$resp)
#   new_freq = as.integer(tsp(avg_mts$resp)[3])
#   index = seq(from=1, to=n, by=1)
#   season = NULL
#   year = NULL
#   curr_year = data$yrs[1] - 1
#   for (i in (1:n)) {
#     if (i %% new_freq == 0) {
#       season = c(season, new_freq)
#     }
#     else {
#       season = c(season, i%%new_freq)
#     }
# 
#     if (i %% new_freq == 1) {
#       year = c(year, curr_year + 1)
#       curr_year = curr_year + 1
#     }
#     else {
#       year = c(year, curr_year)
#     }
#     
#   }
#   df = data.frame(avg_mts, index, season, year)
#   return (df)
# }


as.gasp.data = function(data, window) {
  avg_mts = as.avg(data, window)
  # number of years
  k = length(data$yrs)
  n = length(avg_mts$resp)
  new_freq = as.integer(tsp(avg_mts$resp)[3])
  index = seq(from=1, to=n, by=1)

  if (n %% new_freq != 0) {
    season = rep(c(1:new_freq), times = k-1)
    season = c(season, seq(from=1, to=n %% new_freq, by=1))
    year = rep(data$yrs[-1], each=new_freq)
    year = c(year, rep(data$yrs[length(data$yrs)], times = n %% new_freq))
  }
  else {
    season = rep(c(1:new_freq), times = k)
    year = rep(data$yrs, each=new_freq)
  }

  df = data.frame(avg_mts, index, season, year)
  return (df)
}


```





```{r, echo=TRUE}
ts.subset = function(ts, index) {
  start_year = tsp(ts)[1]
  freq = as.integer(tsp(ts)[3])
  
  start_idx = min(index)
  end_idx = max(index)
  
  start_day = start_idx %% freq
  year_passed = start_idx %/% freq #floor division
  
  subset = ts[start_idx : end_idx]
  # if index is not continuous
  if (length(subset) != length(index)) {
    shifted_idx = index - start_idx + 1
    subset[-shifted_idx] = NA
  }

  return (ts(subset, start=c(start_year+year_passed, start_day),  frequency=freq))
}

```


```{r}
seasonal.shuffle = function(ts) {
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  # number of cycles
  k = ceiling(length(ts)/freq)
  
  equi_class = list()
  for (i in (1:freq)) {

    indices = seq(from=i, to=i+(k-1)*freq, by=freq)
    
    cluster = ts[indices]
    # clear out NA
    cluster = cluster[!is.na(cluster)]
    equi_class[[i]] = cluster

  }
  return (equi_class)
}



```


```{r}
rough.season = function(ts) {
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  # number of cycles
  k = ceiling(length(ts)/freq)
  start_year = as.integer(tsp(ts)[1])
  cycle_copy = unlist(lapply(seasonal.shuffle(ts), FUN=function(x){median(x)}))
  init_season = rep(cycle_copy, k)
  init_season = init_season[1:n]
  return (ts(init_season, start=c(start_year,1), frequency = freq))
}



```





#=======================================================================================
# Seasonal & Trend

LOESS method


# Seasonal
```{r, echo=TRUE}
seasonal = function(ts, deg=2, window=length(ts), iter=4) {
  freq = as.integer(tsp(ts)[3])
  # number of cycles
  k = ceiling(length(ts)/freq)
  start_year = as.integer(tsp(ts)[1])
  # form data frame arranged in same day order
  x = NULL
  y = NULL
  z = NULL
  # buffer is number of traceback days from head or traceforward days from tail
  buffer = ceiling(window / k)
  
  for (i in ((1-buffer):(freq+buffer))) {
    if (i < 1) {
      indices = seq(from=i+freq, to=i+k*freq, by=freq)
    }
    else if (i > freq) {
      indices = seq(from=i-freq, to=i+(k-2)*freq, by=freq)
    }
    else {
      indices = seq(from=i, to=i+(k-1)*freq, by=freq)
    }
    
    cluster = ts[indices]
    # clear out NA
    cluster = cluster[!is.na(cluster)]
    x = c(x, rep(i, length(cluster)))
    y = c(y, cluster)
    # set up marker such that it represents the pos that we should extract the fitted value
    z = c(z, TRUE, rep(FALSE, length(cluster)-1))

  }
  # df = data.frame(x, y)

  # y = rep(y, times = 3)
  # # x = rep(x, times = 3)
  # x = c((x-freq),x,(x+freq))
  # z = rep(z, times = 3)

  span = window / length(ts)

  loess_obj = loess(y ~ x, span=span, degree=deg, family="symmetric", method="loess", control =loess.control(iterations=iter))

  full_period = loess_obj$fitted[which(z==TRUE)][c((buffer+1) : (buffer+freq))]
  seasonality = rep(full_period, k)
  seasonality = seasonality[c(1:length(ts))]

  return (ts(seasonality, start=c(start_year,1), frequency = freq))
}

```







# Trend
```{r, echo=TRUE}
trend = function(ts, deg=2, window=length(ts), iter=4, impute=FALSE) {
  freq = as.integer(tsp(ts)[3])
  start_year = as.integer(tsp(ts)[1])
  n = length(ts)
  y = ts
  x = c(1:n)
  span = window / length(ts)
  loess_obj = loess(y ~ x, na.action=na.exclude, span=span, degree=deg, family="symmetric", method="loess", control=loess.control(surface="direct", iterations=iter))
  na_index = which(is.na(ts))
  # if no NAs
  if (length(na_index) == 0) {
    y = loess_obj$fitted
  }
  # if there are NAs
  else {
    y[-na_index] = loess_obj$fitted
  }

  if (impute) {
    y[na_index] = as.numeric(predict(object=loess_obj, newdata=data.frame(x=na_index)))
  }
  else {
    y[na_index] = NA
  }

  return (ts(y, start = c(start_year,1), frequency = freq))
}





```









#cv.seasonal
```{r, echo=TRUE}
# ts parameter is usually a de-trended time series
cv.seasonal = function(ts, d.max=2, span.min=NULL, span.max=NULL, increment=NULL, fold=5) {
  start_year = tsp(ts)[1]
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  k = ceiling(n/freq) # total number of cycles
  t = round(k/fold) # number of cycles/fold

  # total mean squared error
  minMSE = Inf

  best_degree = 0
  best_span = span.min

  n = length(ts)
  m = length(ts[!is.na(ts)])
  # if (is.null(window.min)) {
  #   # window.min = (10/sqrt(n)) * n
  #   window.min = 0.1 * n
  # }
  # 
  # if (is.null(window.max)) {
  #   # window.max = (20/sqrt(n)) * n
  #   window.max = 0.2 * n
  # }
  
  
  # if (is.null(window.min)) {
  #   window.min = k
  # }
  # 
  # if (is.null(window.max)) {
  #   window.max = 10 * k
  # }

  if (is.null(increment)) {
    # window.min + increment * (steps - 1) = window.max
    # usually do 10 steps
    increment = (span.max - span.min) / (10 - 1)
  }

  for (d in (1:d.max)) {
    for (span in seq(from=span.min, to=span.max, by=increment)) {
      # whole_pred = NULL
      # run 5 times CV
      SSE = 0
      
      for (i in (1:fold)) {
        test_index = seq(from=1+(i-1)*t*freq, to=min(i*t*freq, k*freq), by=1)
        test = ts[test_index]

        train = ts[-test_index]
        train = ts(train, start=c(start_year, 1), frequency = freq)
        
        new_w = span * length(train)
        seasonality = seasonal(train, deg=d, window=new_w)


        pred = seasonality[1:length(test_index)]
        # whole_pred[test_index] = pred
        SSE = SSE + sum((test - pred)^2, na.rm=TRUE)

      }
      # MSE = mean((ts - whole_pred)^2, na.rm=TRUE)
      MSE = SSE / m


      if (MSE < minMSE) {
        best_degree = d
        best_span = span
        minMSE = MSE
      }
    }
  }

  return (data.frame(best_degree, best_span, minMSE))
}

```



```{r, echo=TRUE}
# para: (deg, span)
mse.cv.seasonal = function(ts, deg, span, fold = 5) {
  start_year = tsp(ts)[1]
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  m = length(ts[!is.na(ts)])
  k = ceiling(n/freq) # total number of cycles
  t = round(k/fold) # number of cycles/fold
  
  # throw exception!
  if ((span * n) / k <= 3) {
    return ("span is too small")
  }
  
  
  SSE = 0
  for (i in (1:fold)) {
    test_index = seq(from=1+(i-1)*t*freq, to=min(i*t*freq, k*freq), by=1)
    test = ts[test_index]
    
    train = ts[-test_index]
    train = ts(train, start=c(start_year, 1), frequency = freq)
    
    new_w = span * length(train)
    seasonality = seasonal(train, deg=deg, window=new_w)
    
    
    pred = seasonality[1:length(test_index)]
    # whole_pred[test_index] = pred
    SSE = SSE + sum((test - pred)^2, na.rm=TRUE)
    
  }
  # MSE = mean((ts - whole_pred)^2, na.rm=TRUE)
  MSE = SSE / m
  
  return (MSE)
  
}



```











# Decompositon method
(1) trend -> seasonal

$$X - t_1 = s_1 + \varepsilon_1$$
$$X - s_1 = t_2 + \varepsilon_2$$
$$X - t_2 = s_2 + \varepsilon_3$$
$$\ldots$$
$$X - t_{n-1} = s_{n-1} + \varepsilon_{2n-3}$$
$$X - s_{n-1} = t_n + \varepsilon_{2n-2}$$
$$X - t_n = s_n + \varepsilon_{2n-1}$$




```{r, echo=TRUE}
variation = function(ts, span) {
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  k = ceiling(n/freq)
  s_span_min = 0.1
  s_span_max = 0.5
  s_max = s_span_min * n
  s_min = s_span_max * n
  increment = (s_max - s_min) / 10
  t = trend(ts,window = n*span)
  s_para = cv.seasonal(ts - t,
                         window.min=s_min,
                         window.max=s_max,
                         window.control=increment,
                         fold=5)
  s_window = s_para$best_window
  s_deg = s_para$best_deg
  # s = seasonal(ts-t, window = 0.15*n)
  s = seasonal(ts-t, deg  = s_deg, window = s_window)
  r = ts - s - t
  return (list(sv = var(s, na.rm=TRUE),
               tv = var(t, na.rm=TRUE),
               rv = var(r, na.rm=TRUE)))
}



```






```{r, echo=TRUE}
searchspan = function(ts, span.min, increment) {
  curr_span = span.min
  
  obj = variation(ts, curr_span)
  tv = obj$tv
  rv = obj$rv
  
  diff = tv - rv  # diff > 0 from start until...
  
  # search until diff is negative(or zero) for the first time
  while (diff > 0) {
    curr_span = curr_span + increment
    obj = variation(ts, curr_span)
    tv = obj$tv
    rv = obj$rv
    diff = tv - rv
  }
  return (curr_span)
}



```







```{r, echo=TRUE}
decompose = function(ts, s.deg=1, t.deg=1, s.window=NULL, t.window=NULL, iter=3, cv.control = list(increment=NULL, fold=5)) {
  freq = as.integer(tsp(ts)[3])
  n = length(ts)
  k = ceiling(n/freq)
  true_iter = 2 * iter - 1
  
  t.span = searchspan(ts, span.min=0.01, increment=0.01)

  if (is.null(t.window)) {
    t.window = t.span * n
  }
  
  # if (is.null(s.window)) {
  #   s.window = n * c(10/sqrt(n), 20/sqrt(n))
  # }
  # if (is.null(s.window)) {
  #   s.window = k * c(30, 60)
  # } else {
  #   s.window = k * s.window
  # }
  s.window = k * s.window
  
  if (is.null(cv.control$increment)) {
    cv.control$increment = (max(s.window) - min(s.window)) / 10
  }
  opt_deg = s.deg
  opt_window = n

  prev_season = rep(0, length(ts))
  prev_trend = rep(0, length(ts))
  for (i in (1:true_iter)) {
    if (i == 1) {
      curr_trend = trend(ts, deg=t.deg, window=t.window)
      opt_para = cv.seasonal(ts - curr_trend,
                             window.min=min(s.window),
                             window.max=max(s.window),
                             window.control=cv.control$increment,
                             fold=cv.control$fold)

      opt_deg = opt_para$best_deg
      opt_window = opt_para$best_window
      curr_season = seasonal(ts - curr_trend, deg=opt_deg, window=opt_window)
      prev_trend = curr_trend
      prev_season = curr_season
    }
    else if (i %% 2 == 0) {
      curr_trend = trend(ts - prev_season, deg=t.deg, window=t.window)
      prev_trend = curr_trend
    }
    else {
      opt_para = cv.seasonal(ts - prev_trend,
                             window.min=min(s.window),
                             window.max=max(s.window),
                             window.control=cv.control$increment,
                             fold=cv.control$fold)
      opt_deg = opt_para$best_deg
      opt_window = opt_para$best_window
      curr_season = seasonal(ts - prev_trend, deg=opt_deg, window=opt_window)
      prev_season = curr_season
    }
  }

  remainder = ts - curr_season - curr_trend
  return (list(component = data.frame(raw=ts, seasonal=curr_season, trend=curr_trend, remainder=remainder),
               seasonal.degree = opt_deg,
               seasonal.window = opt_window / k,
               trend.degree = t.deg,
               trend.window = t.window))
}





```



